# Generated by Django 5.2.12 on 2026-03-08 04:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_checkin_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='chk_goal_per_week_1_7',
        ),
        migrations.AddField(
            model_name='checkin',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal_per_week',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.CheckConstraint(condition=models.Q(('goal_per_week__gte', 1)), name='chk_goal_per_week_gte_1'),
        ),
    ]
