# Generated by Django 5.2.12 on 2026-03-19 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_chk_goal_per_week_1_7_checkin_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habit',
            name='uniq_user_title',
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'title'), name='uniq_user_title'),
        ),
    ]
